version: "3.8"
services:
  dmx:
    container_name: "${DEPLOY_PREFIX}-dmx-container"
    restart: always
    image: container-registry.dmx.systems/dmx-contrib/dmx-docker/dmx-latest:alpine-latest
    ports:
      - "${DMX_PORT}:8080"
    environment:
      DEBUG:
      USER_ID: "${user_id}"
      GROUP_ID: "${group_id}"
      DMX_ADMIN_PASSWORD: "${DMX_ADMIN_PASSWORD}"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
    volumes:
      - ./instance/dev-ci/conf:/opt/dmx/conf
      - ./instance/dev-ci/logs:/opt/dmx/logs
      - ./instance/dev-ci/db:/opt/dmx/dmx-db
      - ./instance/dev-ci/filedir:/opt/dmx/dmx-filedir
      - ./instance/dev-ci/bundle-deploy:/opt/dmx/bundle-deploy
      - ./dmx/dev-ci/plugins:/opt/dmx/plugins:ro
      - ./dmx/dev-ci/conf.d:/opt/dmx/conf.d:ro
      - ./dmx/dev-ci/run.d:/opt/dmx/run.d:ro
      - ./dmx/dev-ci/import:/opt/dmx/import:ro


  ldap:
    container_name: "${DEPLOY_PREFIX}-ldap-container"
    restart: unless-stopped
    command: "--copy-service --loglevel debug"
    #command: ["--loglevel debug"]
    build:
      context: "./ldap/${TIER}-ci"
    environment:
      LDAP_OPENLDAP_UID: "${user_id}"
      LDAP_OPENLDAP_GID: "${group_id}"
      LDAP_TLS: "false"
      LDAP_TLS_VERIFY_CLIENT: "never"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
      LDAP_CONFIG_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
    volumes:
      - ./ldap/ldap-db:/var/lib/ldap
      - ./ldap/ldap-cfg:/etc/ldap/slapd.d
      # - ./ldap/certs:/container/service/slapd/assets/certs:ro


  mailhog:
    container_name: "${DEPLOY_PREFIX}-mailhog-container"
    restart: unless-stopped
    image: container-registry.dmx.systems/dmx-intern/docker-images/mailhog:latest
    ports:
      - "${MAIL_PORT}:8025"


  dmxlog:
    container_name: "${DEPLOY_PREFIX}-dmxlog-container"
    restart: unless-stopped
    image: container-registry.dmx.systems/dmx-intern/docker-images/busybox-httpd:latest
    links:
      - dmx
    volumes:
      - ./instance/dev-ci/logs:/home/static/logs:ro
    ports:
      - "${LOGS_PORT}:3000"
